title: "Epidemic"
theme: minima
description: Colin Daniel (Author, maintainer), Leonardo Frid (Author), Alex Embrey (Author)
author: Apex Resource Management Solutions
email: info@apexrms.com
header_pages:
  - index.md
  - getting_started.md
