title: "Epidemic"
theme: minima
description: Colin Daniel (Lead developer), Leonardo Frid (developer), Alex Embrey (developer)
author: Apex Resource Management Solutions
email: info@apexrms.com
header_pages:
  - index.md
  - getting_started.md
