title: "Epidemic"
theme: minima
description: Colin Daniel (Lead developer)<img align="left" style="padding: 8px" width="80" src="assets/images/logo/repository-icon.png">, Leonardo Frid (developer), Alex Embrey (developer)
author: Apex Resource Management Solutions
email: info@apexrms.com
header_pages:
  - index.md
  - getting_started.md
